apiVersion: v1
kind: Service
metadata:
  name: coredns-svc-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: "coredns-external"
  labels:
    k8s-app: coredns-external
spec:
  selector:
    k8s-app: kube-dns
  type:
  loadBalancerIP: 172.17.255.1
  ports:
  - name: tcpdns
    protocol: TCP
    port: 53
    targetPort: 53
---
apiVersion: v1
kind: Service
metadata:
  name: coredns-svc-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: "coredns-external"
  labels:
    k8s-app: coredns-external
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  loadBalancerIP: 172.17.255.1
  ports:
  - name: udpdns
    protocol: UDP
    port: 53
    targetPort: 53
